### ISSUE TITLE
Provide better feedback for fieldtype

### ISSUE THREAD

**Issue by bryanburgers** [markdrzy/geozip#2]
Currently, the input box will change the colors of its border when looking up a zip code, or when a lookup succeeds or fails. I used the fieldtype several times before I noticed this, and I had no indication on whether the lookup succeeded or not.

One solution would be to add icons or text somewhere around the input box to indicate to the user what is happening in a clearer way.

**Comment by markdrzy** [comment]
Added icons in bf93ca90. Validation still needs help, but this should be much more visible than the previous success / error indicator.
